public class ClassFromIDE {
    public static void add() {
        System.debug('**********************Inside the add method.');
    }
    
    public static void addNew() {
        System.debug('**********************Inside the add new method.');
    }
    
    public static void deleteRec() {
        System.debug('**********************Inside the delete method.');
    }
    
    public static void deleteRecNew() {
        System.debug('**********************Inside the delete new method.');
    }
    
    public static void deleteRecOld() {
        System.debug('**********************Inside the delete old method.');
    }
}